application: blockly-test
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
# Storage API.
- url: /storage
  script: storage.app
- url: /storage\.js
  static_files: storage.js
  upload: storage\.js
# Report service.
- url: /report
  script: report.app
# Statistics
- url: /statistics
  script: statistics.app
# Blockly files.
- url: /static
  static_dir: static
# Obsolete URL.
- url: /blockly
  static_dir: static

# Closure library for uncompiled Blockly.
- url: /closure-library-read-only
  static_dir: closure-library-read-only

# Redirect for root directory.
- url: /
  static_dir: static

# Favicon.
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Remote API for backing up data.
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
